# Generated by Django 5.2.12 on 2026-03-16 18:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='managingcompanyyearstat',
            new_name='companies_m_year_8dabd6_idx',
            old_name='companies_m_year_95d08c_idx',
        ),
        migrations.RenameIndex(
            model_name='managingcompanyyearstat',
            new_name='companies_m_year_662996_idx',
            old_name='companies_m_year_84eb54_idx',
        ),
        migrations.AlterField(
            model_name='managingcompanyyearstat',
            name='sum_of_fine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
