# Generated by Django 5.2.12 on 2026-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_companies_m_year_95d08c_idx_companies_m_year_8dabd6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managingcompanyyearstat',
            name='adm_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='managingcompanyyearstat',
            name='final_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managingcompanyyearstat',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
